{% set version = "2.0.0" %}

package:
  name: libastra
  version: {{ version }}

source:
  url: https://github.com/tomopy/astra-toolbox/archive/refs/tags/v{{ version }}-3.tar.gz
  sha256: 1b7e807c3acc4da976475a13104e7601b94edc546dcf775c6b6a86ae3e3fa589

build:
  run_exports:
    - {{ pin_subpackage('libastra', max_pin='x.x.x') }}
  ignore_run_exports:
  # conda-build reports the vs2015_runtime is unused
    - vs2015_runtime  # [win]
  number: 2
  string: "{{ "cuda" + cuda_compiler_version|string }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"
  skip: true  # [not (win64 and cuda_compiler_version == "10.2")]

requirements:
  build:
    # temporary debug
    # - {{ compiler('cuda') }}
    # - {{ compiler('cxx') }}
    # - cmake
    # - ninja 
  # host:
    # - boost-cpp
    # - cudatoolkit
  # run:
  # # unix uses pthread, but win links to libboost:threads
  #   - {{ pin_compatible('boost-cpp', max_pin='x.x') }}  # [win]
  # # astra is written in c++ but seems to prefer including c headers
  #   - ucrt  # [win]
  build:
    - cmake 3.21.3 h39d44d4_0
    - ninja 1.10.2 h2d74725_1
    - nvcc_win-64 10.2 hcf0059e_15
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - vs2015_runtime 14.29.30037 h902a5da_5
    - vs2017_win-64 19.16.27033 hb90652a_3
    - vswhere 2.8.4 h57928b3_0
  host:
    - boost-cpp 1.74.0 h5b4e17d_5
    - bzip2 1.0.8 h8ffe710_4
    - cudatoolkit 10.2.89 hb195166_9
    - libzlib 1.2.11 h8ffe710_1013
    - lz4-c 1.9.3 h8ffe710_1
    - ucrt 10.0.20348.0 h57928b3_0
    - vc 14.2 hb210afc_5
    - vs2015_runtime 14.29.30037 h902a5da_5
    - xz 5.2.5 h62dcd97_1
    - zlib 1.2.11 h8ffe710_1013
    - zstd 1.5.0 h6255e5f_0
  run:
    - boost-cpp >=1.74.0,<1.74.1.0a0
    - cudatoolkit 10.2|10.2.*
    - ucrt
    - vc >=14.1,<15.0a0
test:
  requires:
  # libastra uses header-only from Boost, but the unit tests actually link to libboost_unit_test_framework.so
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
  source_files:
    - tests/astratest  # [unix]
    - tests/astratest.exe  # [win]
  commands:
    - test -f $PREFIX/lib/libastra${SHLIB_EXT}                          # [linux]
    - test -f $PREFIX/lib/libastra${SHLIB_EXT}.0                        # [linux]
    - test -f $PREFIX/lib/libastra${SHLIB_EXT}.0.0.0                    # [linux]
    - "LD_LIBRARY_PATH=$PREFIX/lib:$LD_LIBRARY_PATH ./tests/astratest"  # [unix]
    - if not exist %LIBRARY_LIB%\\AstraCuda64.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\AstraCuda64.dll exit 1  # [win]
    - tests\\astratest                                    # [win]

about:
  home: http://www.astra-toolbox.com
  license: GPL-3.0-only
  license_file:
    - COPYING
    - lib/licenses/rapidxml.txt
  summary: 'libastra is a C++ library of high-performance GPU primitives for 2D
  and 3D tomography.'

extra:
  recipe-maintainers:
    - carterbox
